# Generated by Django 3.2.16 on 2022-11-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fondo_antena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('capital', models.IntegerField()),
                ('fecha', models.DateField()),
                ('informacion', models.CharField(max_length=50)),
                ('detalle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fondo_bomba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('capital', models.IntegerField()),
                ('fecha', models.DateField()),
                ('informacion', models.CharField(max_length=50)),
                ('detalle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fondo_salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('capital', models.IntegerField()),
                ('fecha', models.DateField()),
                ('informacion', models.CharField(max_length=50)),
                ('detalle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pagos_extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_apartamento', models.CharField(max_length=10)),
                ('fecha', models.DateField()),
                ('capital', models.IntegerField()),
                ('detalle', models.CharField(max_length=50)),
                ('informacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pagos_mensuales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('n_apartamento', models.CharField(max_length=10)),
                ('capital', models.IntegerField()),
                ('fecha', models.DateField()),
                ('mes_pago', models.CharField(max_length=10)),
                ('metodo_pago', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
